---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
- Check if the data file exists
    - If data file doesn't exist, check if the zip file exists
        - If zip file doesn't exist, download it
    - Unzip file
- Read in data file

```{R}
if(!file.exists("activity.csv")){
    if(!file.exists("activity.zip")){
        url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
        download.file(url, "activity.zip")
    }
    unzip("activity.zip")
}
activity <- read.csv("activity.csv")

# Convert the date to a date type
activity$date <- as.Date(activity$date, format = "%Y-%m-%d")
str(activity)
```

## What is mean total number of steps taken per day?
##### Create dataset for number of steps daily. Per instructions, missing values may be ignored.
```{R}
activityDailySum <- aggregate(steps ~ date, activity, FUN = sum, na.rm = TRUE)
str(activityDailySum)
```

##### Create histogram for steps per day.
```{R}
hist(activityDailySum$steps, xlab = "Steps Per Day", main = "Histogram of Steps Per Day")
```

##### Calculate mean and median steps per day.
```{R}
mean(activityDailySum$steps)
median(activityDailySum$steps)
```

## What is the average daily activity pattern?
##### Create a dataset for average steps per five-minute intervals across all days.
```{R}
activityIntervalMean <- aggregate(steps ~ interval, activity, FUN=mean, na.rm = TRUE)
str(activityIntervalMean)
```

##### Plot average numbers of steps per 5 minute interval across all days
```{R}
plot(y = activityIntervalMean$steps, x = activityIntervalMean$interval, 
        type = "l", ylab = 'Steps', xlab = 'Interval')
```

##### Find interval with maximum number of steps
```{R}
activityIntervalMean[which.max(activityIntervalMean$steps),]$interval
```
## Imputing missing values
##### Calculate and report total number of missing values
```{R}
nrow(activity[is.na(activity),])
```

##### Fill in all missing values in the dataset.  Missing values will be substituted with the mean value across all days for the given interval.
```{R}
# Merge original data frame with activityIntervalMean
tempActivity <- merge(activity, activityIntervalMean, by = "interval")
# Replace NA values with the interval mean
tempActivity$steps.x[is.na(tempActivity$steps.x)] <- tempActivity$steps.y[is.na(tempActivity$steps.x)]
# Reorder data frame by date and interval
tempActivity <- tempActivity[order(tempActivity$date,tempActivity$interval),]

# Reset row index
rownames(tempActivity) <- NULL
# Create new data set with only columns of interest
activityClean <- tempActivity[,c("steps.x","date","interval")]
# Rename columns to original names
names(activityClean) <- c("steps","date","interval")
str(activityClean)
```

##### Create histogram of total number of steps taken each day
```{R}
hist(aggregate(steps ~ date, activityClean, FUN = sum)$steps, xlab = "Steps Per Day", 
        main = "Histogram of Steps Per Day With Imputed Values")
```

##### Calculate mean and median
```{R}
mean(aggregate(steps ~ date, activityClean, FUN = sum)$steps)
median(aggregate(steps ~ date, activityClean, FUN = sum)$steps)
```

- In the histogram, the distribution remained relatively unchanged between the original data set and the data set with imputed values. The frequency changed, but this is expected as additional values were added.
- The mean did not change between the original data set and the data set with imputed values. This is due to the fact the missing values were replaced with the mean values for the given time interval.
- The median slighly shifted from 10,765 to 10,766.19. This is likely due to the way the distribution very slightly changed to either side of the median based on the introduction of additional values.

## Are there differences in activity patterns between weekdays and weekends?
##### Create factor column in the data set with "Weekend" or "Weekday"
```{R}
weekdays <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
activityClean$dayType <- as.factor(ifelse(weekdays(activityClean$date) %in% weekdays, "Weekday", "Weekend"))
str(activityClean)
# Create necessary data sets
activityDailyFactorSum <- aggregate(steps ~ interval + dayType, activityClean, FUN = mean)
str(activityDailyFactorSum)
```

##### Create panel plot for average steps for weekdays versus weekends
```{R}
library(ggplot2)

g <- ggplot(activityDailyFactorSum, aes(interval, steps))
g <- g + geom_point() + facet_grid(dayType ~ .) + geom_line() 
g <- g + ggtitle("Average Daily Steps: Weekday vs. Weekend") + xlab("Interval") + ylab("Steps")
print(g)
```

- The weekday step average increases earlier in the day than the weekend plot.
- The weekday plot has a higher peak.
- The weekend plot is more consistent through the day.

